---
baseURL: http://localhost
languageCode: en-us
title: tbobm.dev | Local
theme: ["PaperMod"]

enableRobotsTXT: true
buildDrafts: true
buildFuture: true
buildExpired: true

minify:
  disableXML: true
  minifyOutput: true

params:
  env: development
  title: tbobm.dev
  description: "Personal technical blog"
  keywords: [Blog, Portfolio, PaperMod]
  author: 'Theo "Bob" Massard'
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

    #   assets:
    #     # disableHLJS: true # to disable highlight.js
    #     # disableFingerprinting: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    #   label:
    #     text: "Home"
    #     icon: /apple-touch-icon.png
    #     iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: |
      From containers to cloud architecture, I like beautiful and simple things

  socialIcons:
    - name: github
      url: "https://github.com/tbobm"
    - name: linkedin
      url: "https://linkedin.com/in/tbobm"
    - name: medium
      url: "https://medium.com/@tbobm"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/5810495/tbobm"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/tbobm/tbobm-blog/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: now
      name: now
      url: /posts/now/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
