services:
  blog:
    build: .
    ports:
      - 1313:1313
    develop:
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /project

        # Rebuild the image on changes to the `/content/`
        - action: rebuild
          path: ./README.md

