---
site_name: tbobm
site_url: https://blog.tbobm.dev
site_description: Personal technical blog
site_author: Theo "Bob" Massard
google_analytics: ["GTM-WKXDFV6G", "blog.tbobm.dev"]
theme:
  name: simple-blog
  locale: en
